name: Validate Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contracts code
        uses: actions/checkout@v3

      - name: Set up Buf with a specific version
        uses: bufbuild/buf-setup-action@v1
        with:
          # ВАЖЛИВО: Вказуємо конкретну нову версію, яка точно має команду 'dep export'
          version: '1.29.0' 

      # Додатковий крок для перевірки версії (можна потім видалити)
      - name: Verify Buf version
        run: buf --version

      - name: Export Protobuf dependencies using 'buf dep'
        run: |
          cd nexus-contracts
          echo "Exporting Protobuf dependencies..."
          # Ця команда тепер спрацює, оскільки версія buf правильна
          buf export buf.build/googleapis/googleapis --output ../proto-dependencies
          cd ..
