name: Validate Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Validate Docker Compose file
        run: docker-compose -f docker-compose.yaml config

      - name: Validate Kong configuration using Deck
        run: |
          # Встановлюємо deck
          curl -sL https://github.com/kong/deck/releases/download/v1.29.0/deck_1.29.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /usr/local/bin
          
          # Запускаємо валідацію
          deck validate -s ./kong/kong.yaml
